version: '3.9'

services:

  db:
    build:
      context: ./requirements/mariadb
      dockerfile: mariadb
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ~data/mariadb:/var/lib/mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    build: 
      context: ./requirements/wordpress
      dockerfile: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=moi
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ~data/wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ~data/nginx:/var/www/html

volumes:
  data:

networks:
  app-network:
    driver: bridge